name: CI-Firebase-hosting

on:
  push:
    branches:
      - master
      - main
# ...

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # You need to setup node before using the action
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      # Add any steps. For example:
      # - run: npm ci && npm build

      - uses: pchmn/firebase-cli-github-action@main
        with:
          serviceAccountKey: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          projectId: testgithubci-b4476
          # args: deploy --only functions
          # or:
          args: deploy --only hosting
          # args: deploy --only firestore:rules
